steps:
  # 1. Compilar la imagen de Desarrollo explícitamente
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/mi-repo-docker-dev/mi-app:$SHORT_SHA',
      '.'
    ]

  # 2. Subir la imagen al repositorio de Desarrollo
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/mi-repo-docker-dev/mi-app:$SHORT_SHA'
    ]

  # 3. Crear el Release en Cloud Deploy pasando la imagen ya subida
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        LOW_BUILD_ID=$(echo "$BUILD_ID" | tr '[:upper:]' '[:lower:]')
        
        gcloud deploy releases create "rel-dev-$SHORT_SHA-$${LOW_BUILD_ID:0:8}" \
          --delivery-pipeline=mi-pipeline-gke \
          --region=us-central1 \
          --skaffold-file=skaffold.yml \
          --to-target=target-dev \
          --source=. \
          --images="mi-app=us-central1-docker.pkg.dev/$PROJECT_ID/mi-repo-docker/mi-app:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
