steps:
  # 1. Crear el Release en Cloud Deploy activando el perfil de desarrollo
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'rel-dev-$SHORT_SHA-$BUILD_ID'
      - '--delivery-pipeline=mi-pipeline-gke'
      - '--region=us-central1'
      - '--skaffold-file=skaffold.yml'
      - '--to-target=target-dev'
      - '--config-changes=profiles=desarrollo' # 🚀 Activa el perfil de desarrollo en Skaffold

options:
  logging: CLOUD_LOGGING_ONLY
