steps:
  # 1. Crear el Release global en Cloud Deploy (Forzando minúsculas)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        LOW_BUILD_ID=$(echo "$BUILD_ID" | tr '[:upper:]' '[:lower:]')
        
        gcloud deploy releases create "rel-prod-$SHORT_SHA-$${LOW_BUILD_ID:0:8}" \
          --delivery-pipeline=mi-pipeline-gke \
          --region=us-central1 \
          --skaffold-file=skaffold.yml

options:
  logging: CLOUD_LOGGING_ONLY
