steps:
  # 1. Compilar la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/mi-repo-docker/mi-app:$SHORT_SHA',
      '.'
    ]

  # 2. Subir la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/mi-repo-docker/mi-app:$SHORT_SHA'
    ]

  # 3. Crear el Release en Cloud Deploy para gatillar el despliegue automático
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'rel-$SHORT_SHA-$BUILD_ID' # 🚀 Cambiado: Ahora cada intento manual tendrá un nombre único'
      - '--delivery-pipeline=mi-pipeline-gke'
      - '--region=us-central1'
      - '--skaffold-file=skaffold.yml' # 🚀 NUEVA LÍNEA: Vincula explícitamente tu configuración de Skaffold
      - '--images=SET_IMAGE=us-central1-docker.pkg.dev/$PROJECT_ID/mi-repo-docker/mi-app:$SHORT_SHA'

# Redirige los logs directamente a Cloud Logging para permitir el uso de una Service Account personalizada
options:
  logging: CLOUD_LOGGING_ONLY
