apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: mi-pipeline-gke
description: "Pipeline multi-clúster para Dev y Prod"
serialPipeline:
  stages:
  - targetId: target-dev
  - targetId: target-prod
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: target-dev
description: "Clúster de Desarrollo"
gke:
  cluster: projects/gke-lb-multi-backend/locations/us-central1-a/clusters/mi-cluster-gke-dev
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: target-prod
description: "Clúster de Producción"
requireApproval: true
gke:
  cluster: projects/gke-lb-multi-backend/locations/us-central1-a/clusters/mi-cluster-gke-prod
