apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: mi-app-gke

# 1. Configuración base por defecto
build:
  artifacts:
    - image: mi-app
      context: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - kubernetes.yml
deploy:
  kubectl: {}

# 2. Perfiles integrados (Eliminamos el '---' para evitar el error de parsing)
profiles:
  # Se activa solo cuando Cloud Deploy va hacia Desarrollo
  - name: desarrollo
    activation:
      - env: CLOUD_DEPLOY_TARGET=target-dev
    build:
      artifacts:
        - image: us-central1-docker.pkg.dev/gke-lb-multi-backend/mi-repo-docker-dev/mi-app
          context: .

  # Se activa solo cuando Cloud Deploy va hacia Producción
  - name: produccion
    activation:
      - env: CLOUD_DEPLOY_TARGET=target-prod
    build:
      artifacts:
        - image: us-central1-docker.pkg.dev/gke-lb-multi-backend/mi-repo-docker-prod/mi-app
          context: .
